export const MAJORS: string[] = [
    'Accountancy',
    'Acting',
    'Actuarial Science',
    'African and Black Diaspora Studies',
    'American Studies',
    'Animation',
    'Anthropology',
    'Applied Behavioral Sciences',
    'Arabic Studies',
    'Art',
    'Art, Media, and Design',
    'Biochemistry',
    'Biological Sciences',
    'Business Administration',
    'Catholic Studies',
    'Chemistry',
    'Chinese Studies',
    'Comedy Arts',
    'Communication and Media',
    'Communication and Technology',
    'Communication Studies',
    'Composition',
    'Computer Science',
    'Computing',
    'Costume Design',
    'Costume Design and Costume Technology',
    'Costume Technology',
    'Criminology',
    'Cyber - Physical Systems Engineering',
    'Cybersecurity',
    'Data Science',
    'Decision Analytics',
    'Dramaturgy / Criticism',
    'Early Childhood Education',
    'Economics',
    'Elementary Education',
    'English',
    'Environmental Science',
    'Environmental Studies',
    'Exercise Science',
    'Film & Television',
    'Finance',
    'French',
    'Game Design',
    'Game Programming',
    'Geography',
    'German',
    'Graphic Design',
    'Health Sciences',
    'History',
    'History of Art and Architecture',
    'Hospitality Leadership',
    'Information Systems',
    'Information Technology',
    'International Studies',
    'Islamic World Studies',
    'Italian',
    'Japanese Studies',
    'Jazz Studies',
    'Journalism',
    'Latin American and Latino Studies',
    'Leadership Studies',
    'Lighting Design',
    'Management',
    'Marketing',
    'Mathematical Sciences',
    'Mathematics and Computer Science',
    'Media and Cinema Studies',
    'Middle Grades Education',
    'Music',
    'Music Education',
    'Music Performance',
    'Network Engineering and Security',
    'Neuroscience',
    'Nursing',
    'Organizational Communication',
    'Peace, Justice and Conflict Studies',
    'Performing Arts Management',
    'Philosophy',
    'Physical Education',
    'Physics',
    'Playwriting',
    'Political Science',
    'Projection Design',
    'Psychology',
    'Public Policy',
    'Public Relations and Advertising',
    'Real Estate',
    'Religious Studies',
    'Scene Design',
    'Secondary Education',
    'Sociology',
    'Sound Design',
    'Sound Recording Technology',
    'Spanish',
    'Special Education',
    'Sports Communication',
    'Stage Management',
    'Theatre Arts',
    'Theatre Management',
    'Theatre Technology',
    'UserDU Experience Design',
    'Women\'s and Gender Studies',
    'World Language Education',
    'Writing, Rhetoric and Discourse'
];
